name: "godot-ci export"
on: 
  push:
    tags: ["*"]
  pull_request:
    types: [ready_for_review, opened, reopened, auto_merge_enabled]
  merge_group:
    types: [checks_requested]
    
env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: Savor-22b
  PROJECT_PATH: frontend/Savor-22b

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
          fetch-depth: 1

      - name: Add safe.directory configuration
        run: |
          REPO_PATH=$(pwd)
          echo "Repository path is $REPO_PATH"
          git config --global --add safe.directory $REPO_PATH

      - name: Initialize submodules
        run: |
          git submodule sync
          git submodule update --init --recursive
          
      - name: List directory structure for debugging
        run: |
          echo "Listing project directory structure for debugging:"
          ls -R

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows
